In [1]:
from syft.frameworks.torch.mpc.fss import DPF, DIF, N
import numpy as np

In [2]:
keys_a, keys_b = DIF.keygen(n_values=4)

keys_a

array([[101, 185, 254, ..., 102, 126,  38],
       [191,  86, 135, ..., 146,  74, 107],
       [ 81, 221,  73, ...,   2,  66, 117],
       [ 87, 203,  51, ..., 178, 184, 179]], dtype=uint8)

In [3]:
alpha_a = np.frombuffer(np.ascontiguousarray(keys_a[:, 0:N]), dtype=np.uint32).astype(np.uint64)
alpha_b = np.frombuffer(np.ascontiguousarray(keys_b[:, 0:N]), dtype=np.uint32).astype(np.uint64)

alpha_a

array([2885597541,  143087295, 3393838417, 3711159127], dtype=uint64)

In [4]:
x = np.array([[1, 1], [-1, 1]])
x

array([[ 1,  1],
       [-1,  1]])

In [5]:
x_masked = (x + alpha_a.reshape(x.shape) + alpha_b.reshape(x.shape)).astype(np.uint64)
x_masked

array([[4011882847, 1952778245],
       [6760086717, 5519413708]], dtype=uint64)

In [6]:
y0 = DIF.eval(0, x_masked, keys_a)
y1 = DIF.eval(1, x_masked, keys_b)

y0

array([[  858216546,   359345172],
       [-1299791632,  -804553586]])

In [7]:
y0 + y1

array([[0, 0],
       [1, 0]])

In [8]:
import sycret.fss
from sycret.fss import LeFactory  # noqa: 401

In [9]:
help(sycret.fss)


NameError: name 'sycret' is not defined