In [1]:
# Run this cell to see if things work
import sys

import torch
from torch.nn import Parameter
import torch.nn as nn
import torch.nn.functional as F

import syft as sy
hook = sy.TorchHook(torch)

torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [2]:
x = torch.tensor([1,2,3,4,5])
y = x + x
print(y)

tensor([ 2,  4,  6,  8, 10])


In [3]:
bob = sy.VirtualWorker(hook, id="bob")

In [4]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([1,1,1,1,1])

In [5]:
x_ptr = x.send(bob)
y_ptr = y.send(bob)

In [6]:
x_ptr

(Wrapper)>[PointerTensor | me:81354387036 -> bob:29953734715]

In [7]:
bob._objects

{29953734715: tensor([1, 2, 3, 4, 5]), 80683824131: tensor([1, 1, 1, 1, 1])}

In [9]:
z = x_ptr + x_ptr
z

(Wrapper)>[PointerTensor | me:47960421466 -> bob:85222486517]

In [10]:
bob._objects

{29953734715: tensor([1, 2, 3, 4, 5]),
 80683824131: tensor([1, 1, 1, 1, 1]),
 85222486517: tensor([ 2,  4,  6,  8, 10])}

In [11]:
x_ptr

(Wrapper)>[PointerTensor | me:81354387036 -> bob:29953734715]

In [12]:
x_ptr.location      # x_ptr在哪个工作节点上

<VirtualWorker id:bob #objects:3>

In [13]:
bob

<VirtualWorker id:bob #objects:3>

In [14]:
bob == x_ptr.location

True

In [15]:
x_ptr.id_at_location    # x_ptr在其工作节点上的id

29953734715

In [16]:
x_ptr.owner

<VirtualWorker id:me #objects:0>

In [17]:
me = sy.local_worker
me

<VirtualWorker id:me #objects:0>

In [18]:
me == x_ptr.owner

True

In [19]:
x_ptr

(Wrapper)>[PointerTensor | me:81354387036 -> bob:29953734715]

In [20]:
x_ptr.get()

tensor([1, 2, 3, 4, 5])

In [21]:
y_ptr
y_ptr.get()

tensor([1, 1, 1, 1, 1])

In [22]:
z.get()

tensor([ 2,  4,  6,  8, 10])

In [23]:
bob._objects

{}

In [24]:
x = torch.tensor([1,2,3,4,5.], requires_grad=True).send(bob)
y = torch.tensor([1,1,1,1,1.], requires_grad=True).send(bob)

In [25]:
z = (x + y).sum()

In [26]:
z

(Wrapper)>[PointerTensor | me:69709063386 -> bob:34862290451]

In [27]:
z.backward()

(Wrapper)>[PointerTensor | me:89641662345 -> bob:57132970771]

In [28]:
x = x.get()

In [29]:
x

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [30]:
x.grad

tensor([1., 1., 1., 1., 1.])